-- work_daysテーブルにKPI項目を追加
ALTER TABLE work_days ADD COLUMN IF NOT EXISTS contract_target INTEGER DEFAULT 0;
ALTER TABLE work_days ADD COLUMN IF NOT EXISTS visit_count INTEGER DEFAULT 0;
ALTER TABLE work_days ADD COLUMN IF NOT EXISTS negotiation_count INTEGER DEFAULT 0;
ALTER TABLE work_days ADD COLUMN IF NOT EXISTS indoor_count INTEGER DEFAULT 0;
ALTER TABLE work_days ADD COLUMN IF NOT EXISTS contract_count INTEGER DEFAULT 0;
